### ISSUE TITLE
Can't run docker maven plugin

### ISSUE THREAD

**Issue by submind** [carnellj/spmia-chapter2#3]
I tried to follow the instruction in the readme file: 
**mvn clean package docker:build** 
But after running this in command line, I got the following error message:

**[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.0.0:build (default-cli) on project licensing-service: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]**

My environment:
_[Maven]_
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
_[Docker]_
Docker version 1.8.0, build 0d03096

Any help is appreciated! Thanks!

**Comment by carnellj** [comment]
Hi,

Dumb question, but do you have Docker running when you do the build.  I got
the exact error message when I try to build and the Docker daemon is not
running.  You might want to try restarting Docker if it was runninng.

     Thanks,
          John

**Comment by submind** [comment]
Hi John,

Thanks for your reply. Sorry for asking this dumb question, I'm pretty new for docker. By following your instruction, I reinstalled the docker, and then it works! Thank you!

Best

**Comment by submind** [comment]
Works after reinstalling docker.

**Comment by carnellj** [comment]
Not a dumb mistake at all.  I have done it more times then I can count.

Thanks for buying the book.   Hope you enjoy it.

    Thanks,
          John
