### ISSUE TITLE
Deprecated spotify docker-maven-plugin

### ISSUE THREAD

**Issue by kts102121** [carnellj/spmia-chapter2#7]
Hi!

I just purchased the Korean translated version of this book and noticed that the spotify docker-maven-plugin is in bug-fix only phase.

there is a new plugin [spotify](https://github.com/spotify/dockerfile-maven)

Would it be possible to update the pom file to use the new plugin? 

Thanks!

**Comment by carnellj** [comment]
Hi Taesu,

Thank you for your email.  And thank you for purchasing my book.  I did
write a article on medium about 1.5 years ago on this topic.
https://medium.com/@johncarnell/spotify-docker-maven-plugin-changes-by-john-carnell-eb4a7d372f86
. This article shows how to switch to a different plugin.

    Thanks,
          John

**Comment by kts102121** [comment]
I was researching this and found out there is an official guide from the spring guys!

[Spring Boot with Docker](https://spring.io/guides/gs/spring-boot-docker/)

I have combined this with yours and it works well :)
